import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google"
import "./globals.css";
import { cn } from "@/lib/utils";
import Sidebar from './../components/Sidebar';

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
    <body className={`${fontSans.className} flex flex-col md:flex-row`}>
        <Sidebar></Sidebar>
        <main className="w-full h-full flex-grow">
            {children}
        </main>
    </body>
  </html>
  );
}
